---
- hosts: all
  become: yes  
  
  tasks:   
    - name: Update apt-get repo and cache
      ansible.builtin.apt: 
        update_cache: yes 
        force_apt_get: yes 
    
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: latest
        update_cache: true
      with_items:
        - python3-docker
        - docker

    # - name: Install Docker
    #   ansible.builtin.apt:
    #     name: docker
    #     state: present
    

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Reload service to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes
        
    - name: Populate service facts
      service_facts:
    - debug:
        msg: Docker installed!
      when: "'docker' in services"

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Run hello-world
      docker_container:
        name: hello-world
        image: hello-world:latest
        interactive: yes
        detach: false
      register: container_output

    - name: Print container message
      service_facts:
    - debug:
        msg: "{{ container_output }}"   
    # - name: Run hello-world
    #   docker_container:
    #     name: hello-world
    #     image: library/hello-world
    #     pull: true
    # - name: pull an image
    #   docker_image:
    #     name: hello-world
    #     source: pull
    
    # - name: Create a directory if it does not exist
    #   ansible.builtin.file:
    #     path: /tmp/files
    #     state: directory
    #     mode: '0777'
    # - name: Copy file with owner and permissions
    #   ansible.builtin.copy:
    #     src: ./hello-world
    #     dest: /tmp/files/hello-world
    #     mode: '0666'